name: Build with Red Hat UBI8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Red Hat UBI8 Docker Image
      run: docker pull redhat/ubi8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Project with Red Hat UBI8
      run: |
        docker buildx create --use
        docker build -t rhel8 .
        docker run --rm rhel8 make build_internal
        
  build_with_ubi9:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Red Hat UBI9 Docker Image
      run: docker pull redhat/ubi9

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Project with Red Hat UBI9
      run: |
        docker buildx create --use
        docker build -t rhel9 -f Dockerfile.ubi9 .
        docker run --rm rhel9 make build_internal
